import {writeFile} from 'node:fs/promises';
import {catalog,catalogPackage} from '../catalog.mjs';
const dir=new URL('../catalogs/',import.meta.url),date='2026-10-09';
const rows=catalog.map(item=>({id:item.sourceId,marka:item.brand,model:item.model,araclar_sayfasi:item.catalogUrl,
 gorsel:item.media?{dosya:item.image,durum:'model_eslesmesi_kontrol_edildi',alt:`${item.brand} ${item.model} — temsilî katalog fotoğrafı`,google_arama:item.imageSearchUrl,kaynak_url:item.media.sourceUrl,lisans:item.media.license,lisans_url:item.media.licenseUrl,fotografci:item.media.photographer,degisiklikler:item.media.changes,kontrol_tarihi:item.media.checkedAt}:{...item.imageMetadata,durum:'uygun_gorsel_dogrulanamadi'},
 fiyat:{...item.priceMetadata,guncel_fiyat_tl:null,durum:'guncel_fiyat_dogrulanamadi'},
 gecmis_ilan_ornekleri:item.priceSamples,arastirma:item.priceResearch,onceki_kayit:item.originalRecord,logo:item.logoMetadata}));
const report={createdAt:date,brands:catalogPackage.brandCount,modelCount:catalog.length,photosCompleted:catalog.filter(x=>x.image).length,currentPricesVerified:0,modelsWithHistoricalExamples:catalog.filter(x=>x.priceSamples.length).length,historicalExamples:catalog.reduce((n,x)=>n+x.priceSamples.length,0),notes:['178 model korundu; teknik bilgiler ve güncel fiyatlar tahmin edilmedi.','İlan örnekleri arama dizininin tarihî kayıtlarıdır; Ekim 2026 aktif ilanları olarak doğrulanmadı.','Sahibinden 429 ve Arabam doğrudan erişimi 403 verdi; erişim engeli aşılmadı.','Fotoğraflar lisans ve kaynak atfıyla, temsilî katalog fotoğrafı olarak kullanılır.'],models:catalog.map(x=>({id:x.sourceId,brand:x.brand,model:x.model,image:x.image,imageStatus:x.image?'completed':'unavailable_or_rejected',priceStatus:'current_unverified',historicalExamples:x.priceSamples.length,researchSources:x.priceResearch?.sources||[],imageResearch:x.imageResearchDetail}))};
await writeFile(new URL('otoiz_katalog_guncel.json',dir),JSON.stringify({marka_adi:'OTOİZ',olusturma_tarihi:date,marka_sayisi:catalogPackage.brandCount,model_sayisi:rows.length,araclar:rows},null,2));
await writeFile(new URL('entegrasyon-raporu.json',dir),JSON.stringify(report,null,2));
await writeFile(new URL('OTOIZ_OKU_GUNCEL.txt',dir),`OTOİZ — güncellenmiş katalog paketi\nAraştırma tarihi: ${date}\n${report.brands} marka / ${report.modelCount} model\nKontrol edilmiş temsilî fotoğraf: ${report.photosCompleted}\nGeçmiş ilan örneği bulunan model: ${report.modelsWithHistoricalExamples}\nGeçmiş ilan örneği: ${report.historicalExamples}\nDoğrulanmış güncel fiyat: 0\n\nGüncel JSON: catalogs/otoiz_katalog_guncel.json\nGüncel CSV: catalogs/otoiz_arastirma_guncel.csv\nModel bazında tamamlanma/eksik durumu: catalogs/entegrasyon-raporu.json\nFotoğraf lisansları ve atıfları: catalogs/FOTOGRAF-KAYNAKLARI.md\nFotoğraflar: public/araclar/\nOTOİZ logoları: public/logo-light.svg ve public/logo-dark.svg\n\nFotoğraflar gerçek satış ilanı fotoğrafları değildir. Fiyatlar kaynak tarihli geçmiş arama dizini örnekleridir; güncel Türkiye piyasa fiyat listesi değildir. Google görsel arama bağlantıları korunur; fotoğraf dosyaları lisansı doğrulanan Wikimedia Commons kaynaklarından indirilmiştir. Orijinal paket dosyaları değiştirilmeden saklanır. Eksik veri uydurulmaz.\n\nSite zaten bu verilerle entegre edilmiştir. Yeniden dışa aktarmak için proje klasöründe node scripts/export-catalog.mjs; ZIP için powershell -NoProfile -ExecutionPolicy Bypass -File scripts/package-catalog.ps1 çalıştırın. ZIP hesap, oturum, özel data klasörü, .env veya Node yürütülebilir dosyası içermez.\n\nFotoğrafı doğrulanamayan modeller:\n${report.models.filter(x=>!x.image).map(x=>'- '+x.brand+' '+x.model).join('\n')}\n`);
const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';
const csv=[['id','marka','model','gorsel_dosyasi','gorsel_kaynak','lisans','fotografci','guncel_fiyat_tl','ornek_ilan_fiyati_tl','ornek_yil','ornek_km','ilan_tarihi','arastirma_tarihi','fiyat_kaynagi','fiyat_durumu']];
for(const item of catalog)for(const sample of item.priceSamples.length?item.priceSamples:[null])csv.push([item.sourceId,item.brand,item.model,item.image,item.media?.sourceUrl,item.media?.license,item.media?.photographer,null,sample?.amount,sample?.year,sample?.km,sample?.listingDateText,sample?.checkedAt||date,sample?.sourceUrl,sample?'Geçmiş dizin örneği; güncel fiyat doğrulanmadı':'Güncel fiyat doğrulanmadı']);
await writeFile(new URL('otoiz_arastirma_guncel.csv',dir),'\ufeff'+csv.map(row=>row.map(quote).join(',')).join('\r\n')+'\r\n');
await writeFile(new URL('FOTOGRAF-KAYNAKLARI.md',dir),'# OTOİZ fotoğraf kaynakları\n\nFotoğraflar satılık ilan fotoğrafları değildir; temsilî katalog görselleridir. Wikimedia küçük sürümleri indirilmiştir; arayüz object-fit kadrajı kırpabilir.\n\n'+catalog.filter(x=>x.image).map(x=>`- **${x.brand} ${x.model}**: ${x.image} — ${x.media.photographer}; [${x.media.license}](${x.media.licenseUrl||x.media.sourceUrl}); [Kaynak ve özgün dosya](${x.media.sourceUrl}).`).join('\n'));
console.log(JSON.stringify({models:report.models.length,photos:report.photosCompleted,historicalModels:report.modelsWithHistoricalExamples,historicalSamples:report.historicalExamples}));
