import {readFile,writeFile,mkdir} from 'node:fs/promises';
const root=new URL('../',import.meta.url),path=name=>new URL(name,root);
const data=JSON.parse(await readFile(path('catalogs/otoiz_katalog.json'),'utf8'));
const requested=new Set((process.argv[2]||'').split(',').filter(Boolean));
const exteriorOnly=process.argv.includes('--front');
let assets={};try{assets=JSON.parse(await readFile(path('catalogs/media.json'),'utf8'));}catch{}
await mkdir(path('public/araclar/'),{recursive:true});
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
function query(row){const overrides={'renault-r12':'Renault 12','renault-r9-broadway':'Renault 9','renault-r11-flash':'Renault 11','fiat-131-sahin':'Tofas Sahin','fiat-egea':'Fiat Tipo 2016','fiat-124':'Fiat 124 sedan','mini-classic-mini':'Austin Mini','mini-cooper':'Mini Cooper F56','mini-cooper-s':'Mini Cooper S F56','mini-clubman':'Mini Clubman F54','lexus-ls':'Lexus LS 460','citroen-c3':'Citroen C3 2019','citroen-c4':'Citroen C4 2015','mg-mg5':'MG5 EV','mg-mg3':'MG3 2024','ds-ds-3':'DS 3','ds-ds-4':'DS 4','ds-ds-5':'DS 5','ds-ds-7':'DS 7','mazda-mazda3':'Mazda 3','mazda-mazda6':'Mazda 6','mg-mg-zs':'MG ZS','mg-mg-hs':'MG HS','ferrari-360':'Ferrari 360 Modena','ferrari-458':'Ferrari 458 Italia'};return overrides[row.id]||`${row.marka} ${row.model.replace(/ [35] Serisi/,'').replace(' Serisi',' Class')}`;}
function exteriorQuery(row){return {'fiat-124':'Fiat 124','citroen-c3':'Citroen C3','citroen-c4':'Citroen C4','ds-ds-3':'DS3','ds-ds-5':'DS5','ds-ds-7':'DS7','alfa-romeo-giulietta':'Alfa Romeo Giulietta 2012','mini-cooper':'Mini Cooper 2015','mini-cooper-s':'Mini Cooper S 2014','mini-clubman':'Mini Clubman 2016'}[row.id]||query(row);}
function matchesWords(words,tokens,title){return words.every((word,index)=>{const value=norm(word);if(/^\d+$/.test(word)&&Number(word)<1000){const previous=norm(words[index-1]);return tokens.includes(previous+value)||tokens.includes(value+norm(words[index+1]))||tokens.some((token,i)=>token===previous&&tokens[i+1]===value);}if(/^\d+$/.test(word))return tokens.includes(value);if(word.length<3)return tokens.includes(value)||tokens.some(t=>new RegExp('^'+value+'\\d+$').test(t))||tokens.includes(norm(words[index-1])+value);return title.includes(value);});}
async function api(params){const url=new URL('https://commons.wikimedia.org/w/api.php');url.search=new URLSearchParams({action:'query',format:'json',...params});const response=await fetch(url,{headers:{'User-Agent':'OTOIZCatalogResearch/1.0 (educational catalog; attribution retained)'},signal:AbortSignal.timeout(20000)});if(!response.ok){const error=new Error('Commons HTTP '+response.status);error.rateLimited=response.status===429;throw error;}return response.json();}
for(const [index,row]of data.araclar.entries()){
 if(requested.size&&!requested.has(row.id))continue;
 if(assets[row.id]?.file&&!requested.size)continue;
 await new Promise(resolve=>setTimeout(resolve,10000));
 try{
  const term=exteriorOnly?exteriorQuery(row):query(row),words=term.split(' '),found=await api({generator:'search',gsrnamespace:'6',gsrsearch:words.map(w=>'"'+w+'"').join(' ')+(exteriorOnly?' front':'')+' filetype:bitmap -intitle:interior -intitle:wheel -intitle:concept -intitle:prototype -intitle:cockpit -intitle:rally',gsrlimit:'12',prop:'imageinfo',iiprop:'url|extmetadata|size',iiurlwidth:'960'});
  const candidates=Object.values(found.query?.pages||{}).filter(p=>{
   const i=p.imageinfo?.[0],title=norm(p.title),tokens=p.title.toLowerCase().split(/[^a-z0-9]+/);return i&&/\.(jpg|jpeg|png)$/i.test(p.title)&&matchesWords(words,tokens,title)&&i.width>=640&&i.width>i.height&&i.width/i.height<2.7&&clean(i.extmetadata?.Artist?.value)&&!/interior|engine|logo|badge|wheel|dashboard|\btoy\b|modelcar|diecast|crash|wreck|\bXFL\b|flop|formula|\bF1\b/i.test(p.title)&&/^(CC BY(?:-SA)? [234]\.0|CC0|Public domain)$/i.test(clean(i.extmetadata?.LicenseShortName?.value));
  }).filter(p=>!(/railway|train|station|truck|bus | scale |model car|die.?cast|audi a[346]l |prototype|concept|cockpit|panel|antenna|infrared|therm|racing|race |rally|wrc|gtc|tipo 33|wheel|detail|nintendo|console|machine.?gun|weapon|\bvan\b|police|custom estate|\bLWB\b/i.test(p.title))).filter(p=>row.id!=='suzuki-vitara'||!p.title.includes('Grand')).filter(p=>row.id!=='jeep-cherokee'||!p.title.includes('Grand')).filter(p=>row.id!=='byd-seal'||!p.title.includes('Seal U')).sort((a,b)=>{const score=p=>(/front|avant|frontal/i.test(p.title)?3:0)-(/rear|back|heck/i.test(p.title)?2:0);return score(b)-score(a);});
  const chosen=candidates[0];if(!chosen){assets[row.id]={status:'no_licensed_matching_image',query:term,checkedAt:'2026-10-09'};continue;}
  const info=chosen.imageinfo[0],url=info.thumburl||info.url;if(!['upload.wikimedia.org','commons.wikimedia.org','thumb.wikimedia.org'].includes(new URL(url).hostname))throw new Error('Unexpected image host');
  const response=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('Image HTTP '+response.status);const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length<1000||bytes.length>8*1024*1024||!(bytes[0]===255&&bytes[1]===216||bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))))throw new Error('Invalid image bytes');
  const extension=bytes[0]===255?'jpg':'png',file=`/araclar/${row.id}.${extension}`;await writeFile(path('public'+file),bytes);
  assets[row.id]={file,status:'candidate_pending_visual_review',title:chosen.title,sourceUrl:info.descriptionurl,downloadUrl:url,license:clean(info.extmetadata.LicenseShortName.value),licenseUrl:clean(info.extmetadata.LicenseUrl?.value),photographer:clean(info.extmetadata.Artist?.value),description:clean(info.extmetadata.ImageDescription?.value),changes:'Wikimedia thumbnail resize; displayed with CSS object-fit crop',checkedAt:'2026-10-09',query:term};
 }catch(error){assets[row.id]={status:'unavailable',reason:error.message,checkedAt:'2026-10-09'};if(error.rateLimited){console.log('Commons rate limit; stopping without bypassing.');break;}}
 finally{await writeFile(path('catalogs/media.json'),JSON.stringify(assets,null,2));if(index%10===0)console.log(`Images researched ${index+1}/${data.araclar.length}; downloaded ${Object.values(assets).filter(x=>x.file).length}`);}
}
console.log('Image research complete',Object.values(assets).filter(x=>x.file).length);
